package es.alvaro.serna.a10daysapp.model

import es.alvaro.serna.a10daysapp.R

object StrawHatRepository {
    val strawHats = listOf(
        StrawHat(
            R.string.day1,
            R.string.mugiwara1,
            R.string.alias1,
            R.string.description1,
            R.drawable.luffy
        ),
        StrawHat(
            R.string.day2,
            R.string.mugiwara2,
            R.string.alias2,
            R.string.description2,
            R.drawable.zoro
        ),
        StrawHat(
            R.string.day3,
            R.string.mugiwara3,
            R.string.alias3,
            R.string.description3,
            R.drawable.nami
        ),
        StrawHat(
            R.string.day4,
            R.string.mugiwara4,
            R.string.alias4,
            R.string.description4,
            R.drawable.usopp
        ),
        StrawHat(
            R.string.day5,
            R.string.mugiwara5,
            R.string.alias5,
            R.string.description5,
            R.drawable.sanji
        ),
        StrawHat(
            R.string.day6,
            R.string.mugiwara6,
            R.string.alias6,
            R.string.description6,
            R.drawable.chopper
        ),
        StrawHat(
            R.string.day7,
            R.string.mugiwara7,
            R.string.alias7,
            R.string.description7,
            R.drawable.nico_robin
        ),
        StrawHat(
            R.string.day8,
            R.string.mugiwara8,
            R.string.alias8,
            R.string.description8,
            R.drawable.franky
        ),
        StrawHat(
            R.string.day9,
            R.string.mugiwara9,
            R.string.alias9,
            R.string.description9,
            R.drawable.brook
        ),
        StrawHat(
            R.string.day10,
            R.string.mugiwara10,
            R.string.alias10,
            R.string.description10,
            R.drawable.jinbe
        )
    )
}